"""empty message

Revision ID: 26f8bc9eccef
Revises: 3661c412ed86
Create Date: 2024-07-06 20:56:03.441633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f8bc9eccef'
down_revision = '3661c412ed86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('launderer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('launderer', schema=None) as batch_op:
        batch_op.drop_column('desc')

    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('desc')
        batch_op.drop_column('c_type')

    # ### end Alembic commands ###
