"""empty message

Revision ID: 49984ffdec6f
Revises: e31c843bddf7
Create Date: 2024-07-11 15:04:39.651984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49984ffdec6f'
down_revision = 'e31c843bddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundry', schema=None) as batch_op:
        batch_op.alter_column('laundry_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundry', schema=None) as batch_op:
        batch_op.alter_column('laundry_days',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
